apiVersion: batch/v1
kind: Job
metadata:
  name: after
  namespace: default
  lables:
    app: myapp
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: ["sleep", "3"]
      restartPolicy: Never
  backoffLimit: 0
